Feature/tweet detail
givery-bootcamp/dena-2024-team4 pull request #27
Opened 2024-06-17 08:55 UTC by shirataki707

ツイートの詳細を取得できるようにしました。

app.GET("/tweets/:tweetId", controllers.TweetDetail)

2024-06-17 09:27 UTC, shirataki707 commented
パスじゃなくてクエリにした方が良さそう？

2024-06-18 01:35 UTC, ktaroabobon commented
パスでOK！

2024-06-18 01:53 UTC, ktaroabobon requested changes
存在しているIDを取得するところに関してはLGTMです！
存在していないIDを取得するところのエラーハンドリングをお願いします！

2024-06-18 01:53 UTC, ktaroabobon commented on backend/internal/repositories/tweet_detail.go
> +	if result.Error != nil {
ちょっと気になって存在しないpostIdを叩いてみたんだけどなんかゼロ埋めされた値が帰ってくるようになってるっぽい

ここのエラーハンドリングお願いします！IDが存在しない場合は404返してTweet not foundみたいなメッセージ返すと良さそう

<img width="959" alt="image" src="https://github.com/givery-bootcamp/dena-2024-team4/assets/52523218/8425103a-8855-4cb4-8c0d-1f3fba499abd">

2024-06-18 02:37 UTC, shirataki707 commented
404返すようにしました！

`curl -o /dev/null -s -w "%{http_code}\n" http://localhost:9000/tweets/5`
```
404
```

`curl http://localhost:9000/tweets/5 |jq`
```json
{
  "message": "Not found"
}
```

2024-06-18 05:08 UTC, ktaroabobon approved these changes
LGTM!

2024-06-18 05:09 UTC, merged