サインインAPIの実装
givery-bootcamp/dena-2024-team4 pull request #46
Opened 2024-06-18 08:02 UTC by shirataki707

### Issue番号
* #39 

### やったこと
- [x] usernameとpasswordをリクエストで受け取って、アカウントがあるか確認
- [x] userIDを元にJWTを作成してCookieを設定
- [x] ユーザエンティティをレスポンスボディに入れる

### できるようになること（ユーザ目線）
* ログイン認証

### できなくなること（ユーザ目線）
* 特になし

### 動作確認(ローカルでの確認)
* アカウントがある場合
`curl -X POST http://localhost:9000/signin \  -H "Content-Type: application/x-www-form-urlencoded" \
  -d "username=taro_yamada&password=password123"`

```json
{"id":3,"name":"taro_yamada","password":"password123"}
```

* アカウントがない場合
`curl -X POST http://localhost:9000/signin \
  -H "Content-Type: application/x-www-form-urlencoded" \
  -d "username=hoge&password=fuga"  `
```json
{"message":"record not found"}
```

* Cookieの確認
`curl -X POST http://localhost:9000/signin \
  -H "Content-Type: application/x-www-form-urlencoded" \
  -d "username=taro_yamada&password=password123" \
  -c cookies.txt`
`cat cookies.txt`
```
# Netscape HTTP Cookie File
# https://curl.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

#HttpOnly_.localhost    TRUE    /       FALSE   1718783915      jwt     eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTg5NTY3MTUsImlkIjozfQ.pyeQ9lNp8E7E-NbpAGQDGjJSBjwV_KV22HmsX1fLlCs
```

### その他
* どんな形式でリクエストを受け取って、どんな形式でレスポンスを返すのかがよくわかってません
* 現状だとpasswordを含むUserエンティティを返しているのでよくなさそう
* Cookieに設定したりレスポンス返したが、これでサインインAPIの実装が終わったかどうかがわからない

2024-06-24 03:03 UTC, ktaroabobon requested changes
修正お願いします

2024-06-24 03:03 UTC, ktaroabobon commented on backend/internal/repositories/signin_repository.go
> +	result := r.Conn.Where("name = ? AND password = ?", username, password).First(&user)
IDで検索するように変更してほしい！
このままだと同じ名前とパスワードの違う人のアカウント入れちゃう！

2024-06-24 06:55 UTC, shirataki707 commented
jsonとdbのマッピングがうまくいってなかったぽいです。
User structでdb名を追加したら直りました！

```
type User struct {
	ID          int    `json:"id" db:"id"`
	Username    string `json:"username" db:"username"`
	DisplayName string `json:"display_name" db:"display_name"`
	Password    string `json:"password" db:"password"`
}
```

- 検証
`curl -X POST http://localhost:9000/signin -H "Content-Type: application/x-www-form-urlencoded" -d "username=taro123&password=password"`

`{"id":1,"username":"taro123","display_name":"taro","password":"password"}`

2024-06-25 02:29 UTC, ktaroabobon requested changes
SQLの部分に関して修正お願いします！

2024-06-25 02:29 UTC, ktaroabobon commented on mysql/sql/000_create.sql
> +  username      VARCHAR(40)  NOT NULL UNIQUE,
ローカルでは対応できるだけど、本番環境はすでにデータがあることが多いので、sql文は修正ではなく新たにファイルを追加して修正するほうが安全だと思う！
今回だったら`004-add-username-on-users-table.sql`みたいな新たなファイル作ってそこに
- `username`の項目追加
- `name`を`display_name`に変更
- これまで存在するデータに対して変更を加える
みたいにした方がいい

2024-06-25 02:29 UTC, ktaroabobon commented on backend/internal/usecases/signin_usecase.go
> +	tokenString, err := token.SignedString([]byte("secret-key"))
ここのシークレットキーに関しては.envで管理するみたいな方法を取りたいみたいな話だったからそのIssueを作ってもらえると！

2024-06-25 02:29 UTC, ktaroabobon commented on backend/internal/usecases/signin_usecase.go
> +	tokenString, err := token.SignedString([]byte("secret-key"))
一旦このPRの責務外で問題ないかと！

2024-06-25 08:23 UTC, merged