削除APIの作成
givery-bootcamp/dena-2024-team4 pull request #58
Opened 2024-06-25 09:14 UTC by aohana-AO

# 概要
https://github.com/givery-bootcamp/training-app-2024/issues/14

# やったこと
- 以下のエンドポイントで投稿を削除（deleted_atの更新）ができるように修正
`http://localhost:9000/tweets/{ ツイートのid}"`

- レスポンス詳細
       - 200（削除成功）
       - 404（削除するレコードが見つからない）
             -     id検索で見つからない,すでにdeleted_atがnullではない
       - 500（そのほかのエラー） 
# 確認したこと
以下の形式のカールで以下が達成されることを確認
`curl -X DELETE "http://localhost:9000/tweets/{ ツイートのid}"`
- 無事deleted_atが更新されること
- deleted_atがnillでない、そもそもid検索で見つからない場合404を返す

<img width="790" alt="image" src="https://github.com/givery-bootcamp/dena-2024-team4/assets/84378453/af8633a9-5295-42f8-98e5-9061c4bd2e76">

2024-06-26 07:20 UTC, ktaroabobon reviewed
実装ありがとう！
基本的な実装のところは良さそう！

2024-06-26 07:20 UTC, ktaroabobon commented on backend/internal/repositories/tweet_delete.go
> +    if result.Error != nil {
もし可能なら、すでにdeleteされてるtweetに関しては、errorMessageを`Tweet has already deleted`とかにしてあげると良いかも〜

2024-06-27 07:42 UTC, aohana-AO commented on backend/internal/repositories/tweet_delete.go
> +    if result.Error != nil {
直した！

<img width="789" alt="image" src="https://github.com/givery-bootcamp/dena-2024-team4/assets/84378453/d1c15c0e-de30-4654-9d12-269ad3a2bada">

2024-06-27 09:10 UTC, ktaroabobon requested changes
変更あざす！
いくつか変更おねがいします！！

2024-06-27 09:10 UTC, ktaroabobon commented on backend/internal/controllers/tweet_delete_controller.go
> +	tweetIdStr := ctx.Param("tweetId")
```go
request := openapi.NewTweetsDelete~~~()
```
あとはcopilot君にとりあえずおまかせでrequestをパースできるよ！

2024-06-27 09:10 UTC, ktaroabobon commented on backend/internal/controllers/tweet_delete_controller.go
> +	tweetIdStr := ctx.Param("tweetId")
例としてはこんな感じ！
```go
usecase := usecases.NewSignInUsecase()

request := openapi.NewSigninPostRequest()
response404 := openapi.NewError404Response()

if err := ctx.ShouldBindJSON(request); err != nil {
  response404.SetMessage("failed to parse request body")
  ctx.JSON(http.StatusBadRequest, response404)
  return
}
```

2024-06-27 09:10 UTC, ktaroabobon commented on backend/internal/controllers/tweet_delete_controller.go
> +		response404.SetMessage("already deleted")
良き

2024-06-28 07:49 UTC, ktaroabobon approved these changes
LGTM

2024-06-28 08:45 UTC, merged